### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by LittleNightmare** [53m1k0l0n/FFXIV-LazyLoot#12]
i'm using it in CN server. I always meet index out of range issue when i rolling items. Finally, i reverted the code back to its original version to solve this issue. (After changes, do not forget to comment out both `items.AddRange(GetItems())` and `items.Clear()` )

https://github.com/53m1k0l0n/FFXIV-LazyLoot/blob/abc2fc333a459039b875d088839f2ec4091e2eb5/LazyLoot/Plugin/Plugin.cs#L27
```c#
public static List<LootItem> items => ReadArray<LootItem>(lootsAddr + 16, 16).Where(i => i.Valid).ToList();
```

i guess this is an issue of an update. but i am still puzzled as to why INT server does not encounter this problem

**Comment by LittleNightmare** [comment]
and there is still a problem here is not solved, if you are rolling items when you exit the duty will also trigger

**Comment by 53m1k0l0n** [comment]
Greetings.

1. Why are you rolling and leave the dungeon before it's finished rolling? 
2. Please describe as detailed as possible, when you get OutOfRange or do you really mean ALWAYS, because i reversed the rolling direction on purpose to avoid OutOfRange, because i got it, when i rolled from 0 to N and if as example index 1 is rolled and out of the loot pool. But with rolling from N to 0 this shouldn't happend because i don't care if a item on index 5 is removed when i'm at index 4. BUT there is still the possibility to get one. 

As example: Player xyz opens chest in Euphrosyne last boss ( only one chest will be open ) and you roll, while you roll anoth chest get opened and you roll again but in the mean time Item on index 2 is out of loot because Rolled complete by all players and you are on index 5 for the new items from Chest 2. That's why i suggest in Dungeons where at some point are more than 1 Chest wait till all are open and roll.

The problem is i can't test in on CN. I assume you have 5.0.7

Oh and did you only changed Line 27 and this fixed the OutOfRange exception for you? Because like you said, that's strange that you got OutOfRange, but i don't.

Oh and please tell my how your settings look for the plugin.

Have a nice day and see you in your next comment.

**Comment by LittleNightmare** [comment]
For first one:
I was just feeling rolling were slow and didn't want the items, so I left. Maybe check `IsBoundByDuty` before each roll would solve this part.

For second:
I use the compiled net6 version 5.0.7. It is ALWAYS OutOfRange before I change it. In addition to change Line 27, I also comment out both items.AddRange(GetItems()) and items.Clear(). Other than that, nothing else was changed.
Here is my config.
```json
{
  "$type": "LazyLoot.Config.Configuration, LazyLoot",
  "EnableChatLogMessage": true,
  "EnableToastMessage": true,
  "EnableNormalToast": false,
  "EnableErrorToast": false,
  "EnableQuestToast": true,
  "EnableRollDelay": true,
  "RollDelayInSeconds": 1,
  "Version": 0
}
```

I notice you begin 5.0.8 with a lot of changes, i haven't test it. I will try it next time

**Comment by 53m1k0l0n** [comment]
You know what, you have the code, so you could Debug it.
Because it would be awesome to know what is in items for both variants.

**Comment by LittleNightmare** [comment]
i jsut notice what happen:

in my old macro, i run multiple commands
such as
```
/need
/greed
/pass
```
it should be a conflict caused by running the command multiple times. If I understand the c# code correctly, the previous changes made the program take the item list again each time to avoid this problem.
I saw the relevant detection in commits. Even if the previous macro is still used (replaced to the new command), there should be no more errors.

**Comment by 53m1k0l0n** [comment]
Yeah, i implemented a 'over rolling' protection, so now you could hit the macro multiple times but it will go through only once until it's finsished, but i'll implement some Duty leave protection in the next days.
