### ISSUE TITLE
Crash when roll delay set to 0 seconds

### ISSUE THREAD

**Issue by andrewngn13** [53m1k0l0n/FFXIV-LazyLoot#7]
Needs a forced minimum value? Is it possible to set the delay lower than 1 second, such as 500ms?

**Comment by 53m1k0l0n** [comment]
The problem if if you set the Delay too low, i can't guarantee that the roll wil work correctly because, the game needs a bit time to execute the rolling, so if you set it to low it could be possible that the pluging roll pass on a item because it didn't got the info the item is rollled and think you can't get the item. With a delay of 1 second it works, i will try later how it act with like 500ms.

**Comment by 53m1k0l0n** [comment]
Well made some changes, gonna test it, later.

**Comment by 53m1k0l0n** [comment]
Tested protection, to go below a certain value, now it would be possible to set the delay to 0.5 seconds. I'll test later how good this is, in case of looting and checking for the item be rolled.

**Comment by 53m1k0l0n** [comment]
So i tested several runs with 500 ms and i won't suggest it. As long you want the Rolled check, but i will release a new version in the next days with more Settings, and a new feature called FULF if it works how i want.

**Comment by 53m1k0l0n** [comment]
Well it's basically fixed, gonna release it until thursday.
